CREATE DATABASE random_tables;
/c random_tables
CREATE TABLE user(
    user_id int NOT NULL AUTO_INCREMENT PRIMARY KEY,
    username varchar(128) NOT NULL UNIQUE,
    password_hash varchar(16) NOT NULL,
);
CREATE TABLE table (
    table_id int NOT NULL AUTO_INCREMENT PRIMARY KEY,
    created_by NOT NULL FOREIGN KEY,
    name varchar(128) NOT NULL,
);
CREATE TABLE element (
    index int NOT NULL,
    table NOT NULL FOREIGN KEY,
    text varchar(256) NOT NULL,
    PRIMARY KEY(index, table),
);
